/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FeedbackFormService } from "../feedbackForm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FeedbackFormCreateInput } from "./FeedbackFormCreateInput";
import { FeedbackForm } from "./FeedbackForm";
import { FeedbackFormFindManyArgs } from "./FeedbackFormFindManyArgs";
import { FeedbackFormWhereUniqueInput } from "./FeedbackFormWhereUniqueInput";
import { FeedbackFormUpdateInput } from "./FeedbackFormUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FeedbackFormControllerBase {
  constructor(
    protected readonly service: FeedbackFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FeedbackForm })
  @nestAccessControl.UseRoles({
    resource: "FeedbackForm",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFeedbackForm(
    @common.Body() data: FeedbackFormCreateInput
  ): Promise<FeedbackForm> {
    return await this.service.createFeedbackForm({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        partName: true,
        phoneNumber: true,
        updatedAt: true,
        vinCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FeedbackForm] })
  @ApiNestedQuery(FeedbackFormFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FeedbackForm",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbackForms(@common.Req() request: Request): Promise<FeedbackForm[]> {
    const args = plainToClass(FeedbackFormFindManyArgs, request.query);
    return this.service.feedbackForms({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        partName: true,
        phoneNumber: true,
        updatedAt: true,
        vinCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FeedbackForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackForm",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbackForm(
    @common.Param() params: FeedbackFormWhereUniqueInput
  ): Promise<FeedbackForm | null> {
    const result = await this.service.feedbackForm({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        partName: true,
        phoneNumber: true,
        updatedAt: true,
        vinCode: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FeedbackForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackForm",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFeedbackForm(
    @common.Param() params: FeedbackFormWhereUniqueInput,
    @common.Body() data: FeedbackFormUpdateInput
  ): Promise<FeedbackForm | null> {
    try {
      return await this.service.updateFeedbackForm({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          message: true,
          name: true,
          partName: true,
          phoneNumber: true,
          updatedAt: true,
          vinCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FeedbackForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackForm",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFeedbackForm(
    @common.Param() params: FeedbackFormWhereUniqueInput
  ): Promise<FeedbackForm | null> {
    try {
      return await this.service.deleteFeedbackForm({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          message: true,
          name: true,
          partName: true,
          phoneNumber: true,
          updatedAt: true,
          vinCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
